### ISSUE TITLE
[META] content update

### ISSUE THREAD

**Issue by JAicewizard** [lukovdm/bf2-www#230]
- [ ] Update photos page (needs board)
- [ ] Update board picture(s) and texts (needs board)
- [ ] Update committees (needs board)
- [ ] Update confidential advisors (needs board/advisors)
- [ ] Update practice schedule (info is in whatsappgroup, for the course ask lotte)
- [ ] remove SvdM
